# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Ryan Young
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Ryan Young.
# baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: alembic-jekyll-theme
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jemoji
  - liquid_reading_time 

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - Dockerfile
logo: / # We need Alembic to "think" there's a logo for our override to work.
permalink: /:year/:slug/
pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true

# 4. Jekyll settings
sass:
  style: compressed
excerpt_separator: <!-- more -->
timezone: America/Los_Angeles

# 5. Collections
collections:
  writing:
    title: The Blog
    description: Notes on life and the world.
#    feature_text: |
#      Welcome to the blog
    feature_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1c/Manhattan_Bridge_Construction_1909.jpg/2560px-Manhattan_Bridge_Construction_1909.jpg"
  tech:
    title: Tech
    description: Bits, bytes, and blinkin' lights.
#    feature_text: |
#      Welcome to the blog
    feature_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Server_wire_connections.jpg/2560px-Server_wire_connections.jpg"

# 6. Jekyll collections settings
defaults:
  - scope:
      type: posts
    values:
      layout: post
  - scope:
      type: pages
    values:
      layout: page

# 7. Site settings
encoding: utf-8
lang: en-US
disqus: ryanyoung

# 8. Site favicons & manifest icons
favicons:
  16: /assets/favicons/16px.ico
  64: /assets/favicons/64px.png
avatarurl: /assets/favicons/64px.png

# 9. Site navigation
navigation_header:
  - title: About
    url: /
  - title: Portfolio
    url: /portfolio/
  - title: Blog
    url: /blog/
  - title: Tech
    url: /tech/
navigation_footer:
  - title: Jekyll
    url: https://jekyllrb.com/
  - title: Alembic
    url: https://alembic.darn.es/